### ISSUE TITLE
Does this supports multi-gpu training?

### ISSUE THREAD

**Issue by mayfool** [keonlee9420/Soft-DTW-Loss#1]
Thanks for sharing impl of soft-dtw, I can use it in single-gpu env,but can't use it in multi-gpu envs.Currently, it doesn't support multi-gpu training?

**Comment by keonlee9420** [comment]
Hi @mayfool , unfortunately it doesn't support multi-gpu setting. But you can setup multi-gpu and then simply put this as a loss.

**Comment by mayfool** [comment]
Thanks for replying @keonlee9420 . Currently, single gpu training for me is enough.Maybe later I will have a try to use it for multi-gpu setting.
